sudo: required

language: bash

services:
  - docker

before_script:
  - export APP_IMAGE=keboola/processor-create-manifest
  - docker -v
  - docker build -t $APP_IMAGE .
  - docker run $APP_IMAGE composer ci

script:
  # run test job inside KBC
  # - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP $KBC_APP_TEST_CONFIG_ID test
  - skip

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
